markdown: "kramdown"
permalink: "pretty"
future: true

sass:
  style: :compressed

links:
  material:
    Presentation: "https://intro.rustbridge.com"
    Rustlings: "https://github.com/rust-lang/rustlings"
    RustySnakeBook: "https://snake.rustbridge.com/"
    Rust-lang.org: "https://rust-lang.org"
  contact:
    RustBridge: "https://rustbridge.com"
    Email: "mailto:berlin@rustbridge.com"
    Twitter: "https://twitter.com/rustbridgebln"
    "Code of Conduct": "https://rustbridge.com/conduct"

collections:
  events:
    output: true
    permalink: /:collection/:path
